### ISSUE TITLE
minor fixups immediately after Sept-30

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#27] opened 2016-09-27 14:14 UTC
Not high prio, but I would like to see the following quickly solved the week after Sep-30th:

- [x] sed 's/place/country/g' . The term "place" is confusing since currently it is only for a "country". If we are ever to have regions, we might want to make a page about regions
- [x] in the ASN table (country details) once you scroll down in the ASN table, the table header will move to the left. (Google Chrome, latest version)
- [x] improve the sorting arrows : make it more obvious that you can click on the table headers in order to sort
- [ ] Tree map: use color coding (for what? Need to discuss)

**Comment by zelima** [comment] 2016-10-05 11:15
@aaronkaplan Can we say 3 out of 4 above are done? If yes treemap issue becomes duplicate of #22 and we can close this one

**Comment by aaronkaplan** [comment] 2016-10-05 12:51
> On 05 Oct 2016, at 13:15, Irakli Mchedlishvili <notifications@github.com> wrote:
> 
> @aaronkaplan Can we say 3 out of 4 above are done? If yes treemap issue becomes duplicate of #22 and we can close this one
> 

yes, that's good. I still noticed a few minor things with the sorting of the table, but I will create new issues for that. We can close this one and continue in new ones such as #22. Thanks!

**Closed** 2016-10-05 14:07 UTC
Labels: enhancement
