### ISSUE TITLE
[OK] API documentation: parameters not documented on the API page

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#49] opened 2016-09-30 23:46 UTC
Example - how I ran into this topic:

While the API documentation mentions the limit, it is nowhere documented that you actually can add ``&limit=N``. Please add. Similarly , I have no clue which parameters exist (just from reading this page). Soooo....

- [x] please add a documentation on all possible parameters.
- [x] please rename the H1 header "API" to "API v1". This allows us to keep different versions of the API in place and continue to document newer API versions on the same page.

**Comment by zelima** [comment] 2016-10-04 15:20
Not closing this for a while:
Please add checklist for further improvements here if there are some:
- [ ] 
- [ ] 
- [ ]

**Comment by aaronkaplan** [comment] 2016-10-12 14:54
Actually that's a different issue that we just discovered: it seems that the data for /api/v1/risk?risk_id=1 is *not* from the database! It should be calculated from the DB as part of the aggregation step! This is a BUG and not according to what we wanted.

**Comment by rgrp** [comment] 2016-10-13 11:51
I am now not clear what the issue is. Agree that we look at this again once we have a clear shared understanding of what we want to achieve.

**Comment by aaronkaplan** [comment] 2016-10-13 12:21
> On 13 Oct 2016, at 13:51, Rufus Pollock <notifications@github.com> wrote:
> 
> I am now not clear what the issue is. Agree that we look at this again once we have a clear shared understanding of what we want to achieve.
> 

@rgrp: I talked with Irakli about that yesterday that it's a minor thing.
@zelima and me were clear about this yesterday.
pls sync.

**Comment by rgrp** [comment] 2016-10-13 12:55
@aaronkaplan i saw your comment of "please let's talk about this". What was the resolution you reached yesterday?

**Comment by aaronkaplan** [comment] 2016-10-13 13:13
Ah! okay, got it. Confusing. This issue actually addresses multiple issues and at first I only saw the first one. please ignore my previous comment. Re-starting.

- s/Qury string/Query string/   -> trivial. Talked with @zelima about it. Clear and quickly fixable
-  s/place_count/country_count/ (that's in the API output's documentation) -> easy and quickly fixable 
- describe fields in the output. What do they mean? Example of an excellent API description: stat.ripe.net --> easy and not invasive. It's just adding text to the Download page.

More complex and we said we need to talk with @rgrp:
"Actually that's a different issue that we just discovered: it seems that the data for /api/v1/risk?risk_id=1 is not from the database! It should be calculated from the DB as part of the aggregation step! This is a BUG and not according to what we wanted."

So @zelima explained that actually the output of the /api/v1/risk?risk_id=$id is just the previously (old) CSV data. And that it's not calculated by the last import into the DB. That would be wrong. And that should be fixed since it is a feature of BETA-2 to load all the data correctly and to aggregate it and display it.
However, @zelima and me said that this particular issue is more work than just a one hour.
We tried to be fair and reduce the fix-up tasks to < 2 days of total work. This might be more work than 1h. So... let's talk about that. okay? Is it true what we analyzed? How much work is to to calculate the aggregated stats per risk when loading? ...

**Comment by rgrp** [comment] 2016-10-13 14:12
My concern on the second more major item is we have not thought it through properly. E.g. for the risk API the original proposal #7 did not even have querying by id - I am not sure if we need it for now. This is a case where I'd prefer to have a separate substantive issue and we plan it out before we implement it.

I think the other minor items are or will be fixed asap :-)

**Comment by aaronkaplan** [comment] 2016-10-18 11:07
Had a call on FR. Yes, we are going to waive that hard one for BETA-2. Let's move it to BETA-3.

**Comment by rgrp** [comment] 2016-10-20 10:39
FIXED. I think the actual stuff described in original issue description is fixed.

Additional stuff: @aaronkaplan could you describe  the new things you want done in a comment in #82 and i can merge them into a coherent description there.

**Closed by rgrp** 2016-10-20 10:39 UTC
Labels: bug
