### ISSUE TITLE
DNS switch:

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#88] opened 2016-10-31 14:28 UTC
concerning the DNS switch:
We'd like to finally switch the DNS entry for [stats.cybergreen.net](stats.cybergreen.net) to the new BETA-2 site (herokuapp).
Doing a simple CNAME switch does not work.
The ANAME record type is only supported by a single DNS company (easyDNS ?) - so that's also not an option.

Currently following the instructions at https://devcenter.heroku.com/articles/custom-domains
and will prepare everything.

However, the domain needs to first be entered within heroku:
 `heroku domains:add command`

Related to the DNS switch: we need to implement the SSL certificate on the main info site.
What's the best way to?

**Comment by rgrp** [comment] 2016-11-10 12:37
FIXED. Duplicate of https://github.com/cybergreen-net/pm/issues/60

**Closed by rgrp** 2016-11-10 12:37 UTC
